language: scala

env:
  global:
    - SBT_1_0=1.1.0
    - SBT_0_13=0.13.16

stages:
  - test

jobs:
  include:
    - stage: test
      jdk: openjdk8
      env: SBT_SCRIPTED_VERSION=1.1.0
      script: sbt ^^$SBT_1_0 scripted
    - jdk: openjdk8
      env: SBT_SCRIPTED_VERSION=1.0.0
      script: sbt ^^$SBT_1_0 scripted
    - jdk: openjdk6
      env: SBT_SCRIPTED_VERSION=0.13.16
      script: sbt ^^$SBT_0_13 scripted
    - jdk: openjdk6
      env: SBT_SCRIPTED_VERSION=0.13.9
      script: sbt ^^$SBT_0_13 scripted

# Use container-based infrastructure
sudo: false

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache/
    - $HOME/.sbt/boot/
