language: scala

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6

env:
  - SBT_VERSION=0.13.15
  - SBT_VERSION=1.0.0-M5
  - SBT_VERSION=1.0.0-M6

matrix:
  exclude:
  - jdk: openjdk6
    env: SBT_VERSION=1.0.0-M5
  - jdk: oraclejdk7
    env: SBT_VERSION=1.0.0-M5
  - jdk: openjdk6
    env: SBT_VERSION=1.0.0-M6
  - jdk: oraclejdk7
    env: SBT_VERSION=1.0.0-M6

script:
  - sbt ^^$SBT_VERSION test scripted
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

# Use container-based infrastructure
sudo: false

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache/
    - $HOME/.sbt/boot/
